# Generated by Django 4.2.7 on 2023-12-21 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_country_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Город", "verbose_name_plural": "Города"},
        ),
    ]
