# Generated by Django 4.2.5 on 2023-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_description_alter_course_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses"),
        ),
        migrations.AlterField(
            model_name="block",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="courses"),
        ),
        migrations.AlterField(
            model_name="block",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(upload_to="courses"),
        ),
    ]
