# Generated by Django 4.2.7 on 2023-12-21 10:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_alter_answer_date_answeroption"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="courses.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="right",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="answer",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 21, 10, 39, 30, 415983, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="right",
            field=models.BooleanField(default=None),
        ),
    ]
