# Generated by Django 4.2.7 on 2023-12-21 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_answer_question_answer_right_alter_answer_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
