# Generated by Django 4.2.7 on 2023-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_alter_answer_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "Тест", "verbose_name_plural": "Тесты"},
        ),
        migrations.RemoveField(
            model_name="answer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="right",
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_name",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="answer",
            name="options",
            field=models.ManyToManyField(
                through="courses.AnswerOption", to="courses.option"
            ),
        ),
    ]
