# Generated by Django 4.2.7 on 2024-01-10 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_alter_test_options_remove_answer_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answeroption",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="answeroption",
            name="option",
        ),
        migrations.RemoveField(
            model_name="option",
            name="question",
        ),
        migrations.RemoveField(
            model_name="question",
            name="test",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="AnswerOption",
        ),
        migrations.DeleteModel(
            name="Option",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="Test",
        ),
    ]
