# Generated by Django 4.2.7 on 2024-01-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="passed",
            field=models.BooleanField(default=False),
        ),
    ]
