# Generated by Django 4.2.7 on 2024-01-16 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tests", "0003_remove_test_passed_answer_passed_test_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="answer_name",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="date",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="passed",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="user",
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="tests.question",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="right",
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name="test",
            name="mark",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("finish", models.DateTimeField(default=django.utils.timezone.now)),
                ("rezult", models.FloatField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="tests.test",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="answer",
            name="attempt",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="tests.attempt",
            ),
        ),
    ]
