# Generated by Django 4.2.7 on 2024-01-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0006_answer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="options",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="tests.option",
            ),
        ),
    ]
