# Generated by Django 4.2.7 on 2024-01-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0007_alter_answer_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="options",
        ),
        migrations.AddField(
            model_name="answer",
            name="options",
            field=models.ManyToManyField(to="tests.option"),
        ),
    ]
